package com.codemaster.restaurantlisting.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Restaurant {

    // All fields to showcase on the frontEnd on the UI
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO) // id will be auto generated by Hibernate using Hiberate Sequence
    private int id;
    private String name;
    private String address;
    private String city;
    private String restaurantDescription;

}
